name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache-dependency-path: '**/package.json'

      - run: pnpm i
      # - run: pnpm run test-unit
      - run: pnpm run fmt-check
